### ISSUE TITLE
Ошибка при добавлении аккаунтов.

### ISSUE THREAD

**Issue by PIKAPIKARY** [telegram-coin-bot/telegram-coin-bot#10]
Введите номер телефона: 213124124
Введите пароль: 1243513
Данные введены верно? [Y/n] y
Traceback (most recent call last):
  File "/home/siemens/.local/bin/telegram_coin_bot_accounts", line 11, in <module>
    load_entry_point('telegram-coin-bot', 'console_scripts', 'telegram_coin_bot_accounts')()
  File "/home/siemens/src/telegram-coin-bot/telegram_coin_bot/accounts/__main__.py", line 26, in main
    loop.run_until_complete(_main())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/siemens/src/telegram-coin-bot/telegram_coin_bot/accounts/__main__.py", line 19, in _main
    await manage_accounts()
  File "/home/siemens/src/telegram-coin-bot/telegram_coin_bot/accounts/manage_accounts.py", line 73, in manage_accounts
    await actions[action]()
  File "/home/siemens/src/telegram-coin-bot/telegram_coin_bot/accounts/manage_accounts.py", line 10, in add_account
    account = await Account.query.where(Account.phone == phone).gino.first()
  File "/home/siemens/.local/lib/python3.8/site-packages/gino/api.py", line 137, in first
    return await self._query.bind.first(self._query, *multiparams, **params)
  File "/home/siemens/.local/lib/python3.8/site-packages/gino/engine.py", line 748, in first
    return await conn.first(clause, *multiparams, **params)
  File "/home/siemens/.local/lib/python3.8/site-packages/gino/engine.py", line 328, in first
    return await result.execute(one=True)
  File "/home/siemens/.local/lib/python3.8/site-packages/gino/dialects/base.py", line 214, in execute
    rows = await cursor.async_execute(
  File "/home/siemens/.local/lib/python3.8/site-packages/gino/dialects/asyncpg.py", line 184, in async_execute
    result, stmt = await getattr(conn, "_do_execute")(query, executor, timeout)
  File "/home/siemens/.local/lib/python3.8/site-packages/asyncpg/connection.py", line 1423, in _do_execute
    stmt = await self._get_statement(query, None)
  File "/home/siemens/.local/lib/python3.8/site-packages/asyncpg/connection.py", line 328, in _get_statement
    statement = await self._protocol.prepare(stmt_name, query, timeout)
  File "asyncpg/protocol/protocol.pyx", line 163, in prepare
asyncpg.exceptions.UndefinedTableError: relation "accounts" does not exist

**Comment by Parodogs** [comment]
Пробовал? 
`telegram_coin_bot_db upgrade head`
