### ISSUE TITLE
pkg_resources.RequirementParseError: Invalid requirement, parse error at "'-e git+h'"

### ISSUE THREAD

**Issue by PIKAPIKARY** [telegram-coin-bot/telegram-coin-bot#9]
python3 setup.py develop

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 90, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1654, in parseString
    raise exc
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1644, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 3417, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 3739, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 3400, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1406, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 2711, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pkg_resources._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3103, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 92, in __init__
    raise InvalidRequirement(
pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'-e git+h'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 44, in <module>
    install_requires=load_requirements("requirements.txt"),
  File "setup.py", line 17, in load_requirements
    for req in parse_requirements(fp.read()):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3096, in parse_requirements
    yield Requirement(line)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3105, in __init__
    raise RequirementParseError(str(e))
pkg_resources.RequirementParseError: Invalid requirement, parse error at "'-e git+h'"

Никак не могу понять что делать, наверное это чтото связанное с зависимостями. Либо я не понял как правильно устанавливать

**Comment by IvanArttt** [comment]
У меня что то подобное, только не вылазит ошибка, при выполнении команды pip install -e git+htt............. зависает на building wheel for asyncpg setup.py

**Comment by IvanArttt** [comment]
Может это связано

**Comment by IvanArttt** [comment]
а если пропустить этот шаг то 
pip3 install -e .                                                                                                                                                                                   
Obtaining file:///home/kali/Desktop/telegram-coin-bot                                                                                                                                                                                      
    ERROR: Command errored out with exit status 1:                                                                                                                                                                                         
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/kali/Desktop/telegram-coin-bot/setup.py'"'"'; __file__='"'"'/home/kali/Desktop/telegram-coin-bot/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info                                                                                                
         cwd: /home/kali/Desktop/telegram-coin-bot/                                                                                                                                                                                        
    Complete output (47 lines):                                                                                                                                                                                                            
    Traceback (most recent call last):                                                                                                                                                                                                     
      File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 90, in __init__                                                                                                                          
        req = REQUIREMENT.parseString(requirement_string)                                                                                                                                                                                  
      File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1654, in parseString                                                                                                                                  
        raise exc                                                                                                                                                                                                                          
      File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1644, in parseString                                                                                                                                  
        loc, tokens = self._parse( instring, 0 )                                                                                                                                                                                           
      File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache                                                                                                                                
        loc,tokens = self.parseImpl( instring, preloc, doActions )                                                                                                                                                                         
      File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 3417, in parseImpl                                                                                                                                    
        loc, exprtokens = e._parse( instring, loc, doActions )                                                                                                                                                                             
      File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache                                                                                                                                
        loc,tokens = self.parseImpl( instring, preloc, doActions )                                                                                                                                                                         
      File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 3739, in parseImpl                                                                                                                                    
        return self.expr._parse( instring, loc, doActions, callPreParse=False )                                                                                                                                                            
      File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache                                                                                                                                
        loc,tokens = self.parseImpl( instring, preloc, doActions )                                                                                                                                                                         
      File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 3400, in parseImpl                                                                                                                                    
        loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )                                                                                                                                             
      File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1406, in _parseNoCache                                                                                                                                
        loc,tokens = self.parseImpl( instring, preloc, doActions )                                                                                                                                                                         
      File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 2711, in parseImpl                                                                                                                                    
        raise ParseException(instring, loc, self.errmsg, self)                                                                                                                                                                             
    pkg_resources._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)                                                                                                                                      
                                                                                                                                                                                                                                           
    During handling of the above exception, another exception occurred:                                                                                                                                                                    
                                                                                                                                                                                                                                           
    Traceback (most recent call last):                                                                                                                                                                                                     
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3108, in __init__                                                                                                                                              
        super(Requirement, self).__init__(requirement_string)                                                                                                                                                                              
      File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 92, in __init__                                                                                                                          
        raise InvalidRequirement(                                                                                                                                                                                                          
    pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'-e git+h'"                                                                                                                       
                                                                                                                                                                                                                                           
    During handling of the above exception, another exception occurred:                                                                                                                                                                    
                                                                                                                                                                                                                                           
    Traceback (most recent call last):                                                                                                                                                                                                     
      File "<string>", line 1, in <module>                                                                                                                                                                                                 
      File "/home/kali/Desktop/telegram-coin-bot/setup.py", line 44, in <module>                                                                                                                                                           
        install_requires=load_requirements("requirements.txt"),                                                                                                                                                                            
      File "/home/kali/Desktop/telegram-coin-bot/setup.py", line 17, in load_requirements                                                                                                                                                  
        for req in parse_requirements(fp.read()):                                                                                                                                                                                          
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in parse_requirements                                                                                                                                    
        yield Requirement(line)                                                                                                                                                                                                            
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3110, in __init__                                                                                                                                              
        raise RequirementParseError(str(e))                                                                                                                                                                                                
    pkg_resources.RequirementParseError: Invalid requirement, parse error at "'-e git+h'"                                                                                                                                                  
    ----------------------------------------                                                                                                                                                                                               
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by IvanArttt** [comment]
а если и его пропустить то
python3 setup.py development
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 90, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1654, in parseString
    raise exc
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1644, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 3417, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 3739, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 3400, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1406, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 2711, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pkg_resources._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3108, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 92, in __init__
    raise InvalidRequirement(
pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'-e git+h'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 44, in <module>
    install_requires=load_requirements("requirements.txt"),
  File "setup.py", line 17, in load_requirements
    for req in parse_requirements(fp.read()):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in parse_requirements
    yield Requirement(line)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3110, in __init__
    raise RequirementParseError(str(e))
pkg_resources.RequirementParseError: Invalid requirement, parse error at "'-e git+h'"

**Comment by IvanArttt** [comment]
Помогите пожалуйста

**Comment by IvanArttt** [comment]
ох, оставил  я не на долго и вот
 Building wheel for psycopg2-binary (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i3_8rhzy/psycopg2-binary/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i3_8rhzy/psycopg2-binary/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-p2tm8mdl
       cwd: /tmp/pip-install-i3_8rhzy/psycopg2-binary/
  Complete output (40 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-aarch64-3.8
  creating build/lib.linux-aarch64-3.8/psycopg2
  copying lib/errors.py -> build/lib.linux-aarch64-3.8/psycopg2
  copying lib/extras.py -> build/lib.linux-aarch64-3.8/psycopg2
  copying lib/tz.py -> build/lib.linux-aarch64-3.8/psycopg2
  copying lib/_ipaddress.py -> build/lib.linux-aarch64-3.8/psycopg2
  copying lib/compat.py -> build/lib.linux-aarch64-3.8/psycopg2
  copying lib/_lru_cache.py -> build/lib.linux-aarch64-3.8/psycopg2
  copying lib/_range.py -> build/lib.linux-aarch64-3.8/psycopg2
  copying lib/extensions.py -> build/lib.linux-aarch64-3.8/psycopg2
  copying lib/sql.py -> build/lib.linux-aarch64-3.8/psycopg2
  copying lib/errorcodes.py -> build/lib.linux-aarch64-3.8/psycopg2
  copying lib/pool.py -> build/lib.linux-aarch64-3.8/psycopg2
  copying lib/__init__.py -> build/lib.linux-aarch64-3.8/psycopg2
  copying lib/_json.py -> build/lib.linux-aarch64-3.8/psycopg2
  running build_ext
  building 'psycopg2._psycopg' extension
  creating build/temp.linux-aarch64-3.8
  creating build/temp.linux-aarch64-3.8/psycopg
  aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPSYCOPG_VERSION=2.8.5 (dt dec pq3 ext lo64) -DPG_VERSION_NUM=120003 -DHAVE_LO64=1 -I/usr/include/python3.8 -I. -I/usr/include/postgresql -I/usr/include/postgresql/12/server -c psycopg/psycopgmodule.c -o build/temp.linux-aarch64-3.8/psycopg/psycopgmodule.o -Wdeclaration-after-statement
  In file included from psycopg/psycopgmodule.c:28:
  ./psycopg/psycopg.h:36:10: fatal error: libpq-fe.h: No such file or directory
     36 | #include <libpq-fe.h>
        |          ^~~~~~~~~~~~
  compilation terminated.

  It appears you are missing some prerequisite to build the package from source.

  You may install a binary package by installing 'psycopg2-binary' from PyPI.
  If you want to install psycopg2 from source, please install the packages
  required for the build and try again.

  For further information please check the 'doc/src/install.rst' file (also at
  <https://www.psycopg.org/docs/install.html>).

  error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for psycopg2-binary
  Running setup.py clean for psycopg2-binary
Failed to build psycopg2-binary
Installing collected packages: psycopg2-binary, telegram-coin-bot
    Running setup.py install for psycopg2-binary ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i3_8rhzy/psycopg2-binary/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i3_8rhzy/psycopg2-binary/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-c51sfupt/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/kali/.local/include/python3.8/psycopg2-binary
         cwd: /tmp/pip-install-i3_8rhzy/psycopg2-binary/
    Complete output (40 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-aarch64-3.8
    creating build/lib.linux-aarch64-3.8/psycopg2
    copying lib/errors.py -> build/lib.linux-aarch64-3.8/psycopg2
    copying lib/extras.py -> build/lib.linux-aarch64-3.8/psycopg2
    copying lib/tz.py -> build/lib.linux-aarch64-3.8/psycopg2
    copying lib/_ipaddress.py -> build/lib.linux-aarch64-3.8/psycopg2
    copying lib/compat.py -> build/lib.linux-aarch64-3.8/psycopg2
    copying lib/_lru_cache.py -> build/lib.linux-aarch64-3.8/psycopg2
    copying lib/_range.py -> build/lib.linux-aarch64-3.8/psycopg2
    copying lib/extensions.py -> build/lib.linux-aarch64-3.8/psycopg2
    copying lib/sql.py -> build/lib.linux-aarch64-3.8/psycopg2
    copying lib/errorcodes.py -> build/lib.linux-aarch64-3.8/psycopg2
    copying lib/pool.py -> build/lib.linux-aarch64-3.8/psycopg2
    copying lib/__init__.py -> build/lib.linux-aarch64-3.8/psycopg2
    copying lib/_json.py -> build/lib.linux-aarch64-3.8/psycopg2
    running build_ext
    building 'psycopg2._psycopg' extension
    creating build/temp.linux-aarch64-3.8
    creating build/temp.linux-aarch64-3.8/psycopg
    aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPSYCOPG_VERSION=2.8.5 (dt dec pq3 ext lo64) -DPG_VERSION_NUM=120003 -DHAVE_LO64=1 -I/usr/include/python3.8 -I. -I/usr/include/postgresql -I/usr/include/postgresql/12/server -c psycopg/psycopgmodule.c -o build/temp.linux-aarch64-3.8/psycopg/psycopgmodule.o -Wdeclaration-after-statement
    In file included from psycopg/psycopgmodule.c:28:
    ./psycopg/psycopg.h:36:10: fatal error: libpq-fe.h: No such file or directory
       36 | #include <libpq-fe.h>
          |          ^~~~~~~~~~~~
    compilation terminated.

    It appears you are missing some prerequisite to build the package from source.

    You may install a binary package by installing 'psycopg2-binary' from PyPI.
    If you want to install psycopg2 from source, please install the packages
    required for the build and try again.

    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).

    error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i3_8rhzy/psycopg2-binary/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i3_8rhzy/psycopg2-binary/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-c51sfupt/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/kali/.local/include/python3.8/psycopg2-binary Check the logs for full command output.

**Comment by IvanArttt** [comment]
и теперь не зависает, а выходят эти 2 ошибки

**Comment by IvanArttt** [comment]
К тому же pcycopg2 не устанавливается через pip3 install

**Comment by IvanArttt** [comment]
Эта команда решила проблему с установкой библиотек
sudo apt install libpq-dev python3-dev 
Но не решила с pip3 install -e .

**Comment by IvanArttt** [comment]
новая ошибка
 python3 setup.py development
Traceback (most recent call last):
  File "setup.py", line 44, in <module>
    install_requires=load_requirements("requirements.txt"),
  File "setup.py", line 19, in load_requirements
    requirements.append("{}{}{}".format(req.name, extras, req.specifier))
AttributeError: 'Requirement' object has no attribute 'name'

**Comment by IvanArttt** [comment]
pip3 install -e .
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/kali/Desktop/telegram-coin-bot
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/kali/Desktop/telegram-coin-bot/setup.py'"'"'; __file__='"'"'/home/kali/Desktop/telegram-coin-bot/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-xj4oz64b
         cwd: /home/kali/Desktop/telegram-coin-bot/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/kali/Desktop/telegram-coin-bot/setup.py", line 44, in <module>
        install_requires=load_requirements("requirements.txt"),
      File "/home/kali/Desktop/telegram-coin-bot/setup.py", line 19, in load_requirements
        requirements.append("{}{}{}".format(req.name, extras, req.specifier))
    AttributeError: 'Requirement' object has no attribute 'name'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by PIKAPIKARY** [comment]
так что с этой ошибкой? бот просто не работает без установки

**Comment by IvanArttt** [comment]
Появилась новая версия, с инструкцией
